baseurl = "http://www.mrsinham.net/"
title = "MrSinham"
author = "Julien Lefèvre"
copyright = "Copyright (c) 2014, Julien Lefèvre; all rights reserved."
socialsharing = true
disqusShortname = "mrsinham"
Paginate = 10

[params]
    sidebartitle = "Mrsinham's Blog"
    twitterName = "mrsinham"
    githubName = "mrsinham"
    sidebartagline = "IT thoughts"
    google_analytics = "UA-44854344-1"
[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "http://www.twitter.com/mrsinham"
    identifier = "mrsinham"
